name: "selenium grid 4 on  minikube CI workflow"


on:
  push:
    branches: [ test ]
  # schedule:
  #     - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month 
      
      
jobs:

  ubuntu-latest:
    name: "grid 4 on minikube"
    runs-on: ubuntu-latest
    # strategy:
    #       matrix:
    #         kubernetes: [v1.23.0,v1.20.0,v1.19.2,v1.18.9,v1.17.5]       
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Setup Minikube"
        # https://github.com/manusa/actions-setup-minikube
        uses: manusa/actions-setup-minikube@v2.6.0
        with:
          minikube version: "v1.13.1"
          kubernetes version: "v1.19.2"
      - name: "List nodes"
        run: kubectl get nodes          
