name: "Ubuntu kind CI workflow"


on:
  push:
    branches: [ dev ]

jobs:


  ubuntu-latest-kind-job:
    name: "ubuntu-latest kind job"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status
    - name: "check the runner"
      run: |
        ls -l /usr/local/bin/
    # - name: "Update PATH"
    #   run: |
    #     echo $PATH
    #     echo "::add-path::/home/runner/bin"
    - name: "Install k3d" 
      run: make install_k3d    
    - name: "Install argo client"
      run: make install_argo  
    - name: Setup local cluster
      run: |
        make create_cluster
        make switch_context
        make create_namespace               
