name: "Ubuntu build minikube CI workflow"


on:
  push:
    branches: [ test ]

jobs:

  ubuntu-1604-minikube-latest-job:
    name: "ubuntu-16.04 minikube latest job"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
          echo "===================================================================================="
                        hostnamectl status
          echo "===================================================================================="
          echo "         \   ^__^                                                                  "
          echo "          \  (oo)\_______                                                          "
          echo "             (__)\       )\/\                                                      "
          echo "                 ||----w |                                                         "
          echo "                 ||     ||                                                         "
          echo "===================================================================================="  
    # * The "docker" driver should not be used with root privileges.
    # * If you are running minikube within a VM, consider using --driver=none:
    - name: "Build minikube latest cluster"
      # run: sudo make deploy-minikube-latest
      run: make deploy-minikube-latest

  ubuntu-1604-minikube-job:
    name: "ubuntu-16.04 minikube job"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
          echo "===================================================================================="
                        hostnamectl status
          echo "===================================================================================="
          echo "         \   ^__^                                                                  "
          echo "          \  (oo)\_______                                                          "
          echo "             (__)\       )\/\                                                      "
          echo "                 ||----w |                                                         "
          echo "                 ||     ||                                                         "
          echo "===================================================================================="  
    # * The "docker" driver should not be used with root privileges.
    # * If you are running minikube within a VM, consider using --driver=none:      
    - name: "Build minikube cluster"
      # run: sudo make deploy-minikube
      run: make deploy-minikube