name: "Ubuntu minikube jenkins-x CI workflow"


on:
  push:
    branches: [ dev ]

jobs:



  ubuntu-latest-minikube-jenkinsx-job:
    name: "ubuntu-latest minikube job"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
          echo "===================================================================================="
                        hostnamectl status
          echo "===================================================================================="
          echo "         \   ^__^                                                                  "
          echo "          \  (oo)\_______                                                          "
          echo "             (__)\       )\/\                                                      "
          echo "                 ||----w |                                                         "
          echo "                 ||     ||                                                         "
          echo "===================================================================================="
    # https://jenkins-x.io/v3/admin/platforms/minikube/    
    - name: "deploy jenkins-x"
      run: |
        #delete the current cluster
        minikube delete 
        #create a minikube cluster
        minikube start --cpus 4 --memory 8048 --disk-size=100g --addons=ingress --vm=true          
        #minikube start --driver=docker --cpus 4 --memory 8048 --disk-size=100g --addons=ingress --vm=true 
 