name: "Ubuntu minikube CI workflow"


on:
  push:
    branches: [ dev ]

jobs:


  ubuntu-latest-minikube-job:
    name: "ubuntu-latest minikube job"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
          echo "===================================================================================="
                        hostnamectl status
          echo "===================================================================================="
          echo "         \   ^__^                                                                  "
          echo "          \  (oo)\_______                                                          "
          echo "             (__)\       )\/\                                                      "
          echo "                 ||----w |                                                         "
          echo "                 ||     ||                                                         "
          echo "===================================================================================="
    - name: "check the runner"
      run: |
        ls -l /usr/local/bin/
    # - name: "Start a minikube cluster"
    #   run: |
    #     minikube start
    #     n=0; until ((n >= 60)); do kubectl -n default get serviceaccount default -o name && break; n=$((n + 1)); sleep 1; done; ((n < 60)) 
    #     minikube version --components
    #     minikube version --short
    - name: "run Kubernetes on the local host using containers rather than a virtual machine"
      run: |
        minikube delete #delete the current cluster
        #Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=docker
        # minikube start --driver=docker
        minikube start --driver=docker --vm-driver none
        minikube version --short
        minikube version --components
    # https://jenkins-x.io/v3/admin/platforms/minikube/    
    - name: "deploy jenkins-x"
      run: |
        #delete the current cluster
        minikube delete 
        #create a minikube cluster
        minikube start --cpus 4 --memory 8048 --disk-size=100g --addons=ingress --vm=true          
      

  ubuntu-1604-job:
    name: "ubuntu-16.04 minikube job"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Start a minikube cluster"
      run: |
        minikube start
        n=0; until ((n >= 60)); do kubectl -n default get serviceaccount default -o name && break; n=$((n + 1)); sleep 1; done; ((n < 60)) 
    - name: "deploy minikube"
      run: sudo make deploy-minikube   

  # ubuntu-1804-job:
  #   name: "ubuntu-18.04 minikube job"
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "Start a minikube cluster"
  #     run: |
  #       minikube start
  #       n=0; until ((n >= 60)); do kubectl -n default get serviceaccount default -o name && break; n=$((n + 1)); sleep 1; done; ((n < 60)) 


  # ubuntu-2004-job:
  #   name: "ubuntu-20.04 minikube job"
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 
  #   - name: "Start a minikube cluster"
  #     run: |
  #       minikube start
  #       n=0; until ((n >= 60)); do kubectl -n default get serviceaccount default -o name && break; n=$((n + 1)); sleep 1; done; ((n < 60)) 


